pipeline {
   agent any
   environment {
      NAMESPACE = 'customer001'
      VERSION = 'blue'
   }
   stages {
      stage('Prepare') {
         steps {
            sh 'kubectl version --client'
         }
      }
      stage('Swap') {
         steps {
            kubernetesDeploy(
               kubeconfigId:'mykubeconfig',
               configs:'nvx-cms/service.yaml'
            )
         }
      }
   }
}