apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: customer001
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: sonymst.azurecr.io/postgres:10-alpine
        env:
        - name: LANG
          value: en_US.UTF-8
        - name: LANGUAGE
          value: en_US:en
        - name: LC_ALL
          value: en_US.UTF-8
        - name: PGDATA
          value: /var/lib/postgresql/data
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: S0ny@SqlAdm1n
        - name: TZ
          value: Asia/Tokyo
        - name: MAX_CONNECTIONS
          value: "1000"
        resources: 
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: "data"
            mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: data
          hostPath:
            path: "/home/yuta_matsui/sony/data/pgdata"
      imagePullSecrets:
        - name: nvx-service-secret2
