pipeline {
   agent any
   environment {
      // DOCKER_IMAGE_TAG = '1.0.0-SNAPSHOT'
      DOCKER_IMAGE_TAG = 'latest'
      NAMESPACE = 'customer001'
      VERSION = 'blue'
   }
   stages {
      stage('Prepare') {
         steps {
            sh 'kubectl version --client'
         }
      }
      stage('Deploy') {
         steps {
            kubernetesDeploy(
               kubeconfigId:'mykubeconfig',
               configs:'nvx-cms/pv.yaml'
            )
            kubernetesDeploy(
               kubeconfigId:'mykubeconfig',
               configs:'nvx-cms/pvc.yaml'
            )
            kubernetesDeploy(
               kubeconfigId:'mykubeconfig',
               configs:'nvx-cms/deployment.yaml'
            )
            kubernetesDeploy(
               kubeconfigId:'mykubeconfig',
               configs:'nvx-cms/service.yaml'
            )
         }
      }
   }
}