pipeline {
   agent any
   environment {
      DOCKER_IMAGE_TAG = '0.10.0'
      NAMESPACE = 'customer-a'
      VERSION = 'blue'
   }
   stages {
      stage('Prepare') {
         steps {
            sh 'kubectl version --client'
         }
      }
   }
}