apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nvx-cms-data-pvc
  namespace: $NAMESPACE
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
  volumeName: nvx-cms-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nvx-cms-log-pvc
  namespace: $NAMESPACE
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
  volumeName: nvx-cms-log-pv

