pipeline {
   agent any

   stages {
      stage('Prepare') {
         steps {
            sh 'kubectl version --client'
         }
      }
      stage('Deploy') {
         steps {
            kubernetesDeploy(
               kubeconfigId:'mykubeconfig',
               configs:'demo-app/deployment.yaml'
            )
            kubernetesDeploy(
               kubeconfigId:'mykubeconfig',
               configs:'demo-app/service.yaml'
            )
         }
      }
   }
}