pipeline {
   agent any
   environment {
      DOCKER_IMAGE_TAG = '0.12.0'
      NAMESPACE = 'cutomer-a'
      VERSION = 'v1'
   }
   stages {
      stage('Prepare') {
         steps {
            sh 'kubectl version --client'
         }
      }
      stage('Deploy') {
         steps {
            kubernetesDeploy(
               kubeconfigId:'mykubeconfig',
               configs:'demo-app/deployment.yaml'
            )
            kubernetesDeploy(
               kubeconfigId:'mykubeconfig',
               configs:'demo-app/service.yaml'
            )
         }
      }
   }
}