apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo-app
    version: v10
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: demo-app
    version: v10
  type: LoadBalancer
