apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: $NAMESPACE
  labels:
    app: demo-app
    version: $VERSION
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: demo-app
    version: $VERSION
  type: LoadBalancer
