pipeline {
   agent any
   environment {
      DOCKER_IMAGE_TAG = '0.12.0'
      NAMESPACE = 'customer001'
      VERSION = 'blue'
   }
   stages {
      stage('Prepare') {
         steps {
            sh 'kubectl version --client'
         }
      }
      stage('Deploy') {
         steps {
            kubernetesDeploy(
               kubeconfigId:'mykubeconfig',
               configs:'nvx-cms/deployment.yaml'
            )
         }
      }
   }
}