pipeline {
   agent any
   environment {
      NAMESPACE = 'customer-a'
      VERSION = 'v1'
   }
   stages {
      stage('Prepare') {
         steps {
            sh 'kubectl version --client'
         }
      }
      stage('Swap') {
         steps {
            kubernetesDeploy(
               kubeconfigId:'mykubeconfig',
               configs:'demo-app-swap/service.yaml'
            )
         }
      }
   }
}